name: Deploy Only

on:
  workflow_dispatch:   # Permite ejecutarlo manualmente

jobs:
  build_and_push:
    name: Build & Push Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_API_URL }}

      # API Gateway
      - name: Build & Push API Gateway Image
        id: api
        run: |
          TAG=${GITHUB_SHA::8}
          docker build -t ${{ secrets.ECR_API_URL }}:$TAG ./api-gateway
          docker push ${{ secrets.ECR_API_URL }}:$TAG
          echo "API_IMAGE=${{ secrets.ECR_API_URL }}:$TAG" >> $GITHUB_OUTPUT

      # Product
      - name: Build & Push Product Image
        id: product
        run: |
          TAG=${GITHUB_SHA::8}
          docker build -t ${{ secrets.ECR_PRODUCT_URL }}:$TAG ./product-service
          docker push ${{ secrets.ECR_PRODUCT_URL }}:$TAG
          echo "PRODUCT_IMAGE=${{ secrets.ECR_PRODUCT_URL }}:$TAG" >> $GITHUB_OUTPUT

      # Inventory
      - name: Build & Push Inventory Image
        id: inventory
        run: |
          TAG=${GITHUB_SHA::8}
          docker build -t ${{ secrets.ECR_INVENTORY_URL }}:$TAG ./inventory-service
          docker push ${{ secrets.ECR_INVENTORY_URL }}:$TAG
          echo "INVENTORY_IMAGE=${{ secrets.ECR_INVENTORY_URL }}:$TAG" >> $GITHUB_OUTPUT

  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Prepare Task Definition
        id: prepare
        run: |
          cp infra/ecs-task/taskdef.json taskdef.json

          sed -i "s|__API_IMAGE__|${{ needs.build_and_push.outputs.API_IMAGE }}|" taskdef.json
          sed -i "s|__PRODUCT_IMAGE__|${{ needs.build_and_push.outputs.PRODUCT_IMAGE }}|" taskdef.json
          sed -i "s|__INVENTORY_IMAGE__|${{ needs.build_and_push.outputs.INVENTORY_IMAGE }}|" taskdef.json

      - name: Register Task Definition
        id: reg
        run: |
          OUT=$(aws ecs register-task-definition --cli-input-json file://taskdef.json)
          ARN=$(echo $OUT | jq -r '.taskDefinition.taskDefinitionArn')
          echo "TASK_ARN=$ARN" >> $GITHUB_OUTPUT

      - name: Update ECS Service
        run: |
          aws ecs update-service \
            --cluster "${{ secrets.ECS_CLUSTER_NAME }}" \
            --service "${{ secrets.ECS_SERVICE_NAME }}" \
            --task-definition "${{ steps.reg.outputs.TASK_ARN }}" \
            --force-new-deployment \
            --desired-count 1

      - name: Completed
        run: echo "ðŸš€ Deploy ejecutado correctamente."

