name: Deploy Only

on:
  workflow_dispatch:

jobs:
  build_and_push:
    name: Build & Push Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
          | docker login --username AWS --password-stdin ${{ secrets.ECR_API_URL }}

      - name: Build images and save outputs
        id: build_all
        run: |
          TAG=${GITHUB_SHA::8}

          # API
          docker build -t ${{ secrets.ECR_API_URL }}:$TAG ./api-gateway
          docker push ${{ secrets.ECR_API_URL }}:$TAG

          # PRODUCT
          docker build -t ${{ secrets.ECR_PRODUCT_URL }}:$TAG ./product-service
          docker push ${{ secrets.ECR_PRODUCT_URL }}:$TAG

          # INVENTORY
          docker build -t ${{ secrets.ECR_INVENTORY_URL }}:$TAG ./inventory-service
          docker push ${{ secrets.ECR_INVENTORY_URL }}:$TAG

          # Guardamos las imÃ¡genes
          echo "API_IMAGE=${{ secrets.ECR_API_URL }}:$TAG" >> image-outputs.env
          echo "PRODUCT_IMAGE=${{ secrets.ECR_PRODUCT_URL }}:$TAG" >> image-outputs.env
          echo "INVENTORY_IMAGE=${{ secrets.ECR_INVENTORY_URL }}:$TAG" >> image-outputs.env

      - name: Upload image outputs
        uses: actions/upload-artifact@v4
        with:
          name: image-outputs
          path: image-outputs.env

  deploy:
    name: Deploy ECS using Terraform
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download image outputs
        uses: actions/download-artifact@v4
        with:
          name: image-outputs

      - name: Load variables
        id: vars
        run: |
          source image-outputs.env
          echo "api=$API_IMAGE" >> $GITHUB_ENV
          echo "product=$PRODUCT_IMAGE" >> $GITHUB_ENV
          echo "inventory=$INVENTORY_IMAGE" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init (ecs-task)
        working-directory: infra/ecs-task
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: terraform init -input=false

      - name: Terraform Apply (ecs-task)
        working-directory: infra/ecs-task
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          terraform apply -auto-approve \
            -var environment=dev \
            -var cpu=256 \
            -var memory=512 \
            -var apigateway_port=8080 \
            -var product_port=5000 \
            -var inventory_port=4000 \
            -var postgres_port=5432 \
            -var redis_port=6379 \
            -var postgres_image="postgres:latest" \
            -var redis_image="redis:latest" \
            -var ecr_urls='{ 
                apigateway = "'$api'",
                product    = "'$product'",
                inventory  = "'$inventory'"
              }'

      - name: Completed
        run: echo "ðŸš€ Deploy via Terraform ejecutado correctamente."

