name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'El entorno a desplegar'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: "us-east-1"

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init -input=false

      - name: Terraform Plan
        working-directory: infra/terraform
        run: terraform plan -var-file="dev.tfvars" -var="sender_email=${{ secrets.SENDER_EMAIL }}" -var="app_password=${{ secrets.APP_PASSWORD }}" -out=tfplan

      - name: Terraform Apply
        working-directory: infra/terraform
        run: terraform apply -auto-approve tfplan

      - name: Exportar ECR URLs a secretos de GitHub
        working-directory: infra/terraform
        run: |
          echo "Obteniendo outputs individuales (limpio con grep)..."

          API=$(terraform output ecr_api_url | grep -oE "[0-9]+\.dkr\.ecr\.[^ ]+")
          PRODUCT=$(terraform output ecr_product_url | grep -oE "[0-9]+\.dkr\.ecr\.[^ ]+")
          INVENTORY=$(terraform output ecr_inventory_url | grep -oE "[0-9]+\.dkr\.ecr\.[^ ]+")

          echo "=== DEBUG CLEAN ==="
          echo "API: '$API'"
          echo "PRODUCT: '$PRODUCT'"
          echo "INVENTORY: '$INVENTORY'"
          echo "==================="

          echo "Actualizando secretos de GitHub..."
          gh secret set ECR_API_URL       --body "$API"
          gh secret set ECR_PRODUCT_URL   --body "$PRODUCT"
          gh secret set ECR_INVENTORY_URL --body "$INVENTORY"
        env:
          GH_TOKEN: ${{ secrets.REPO_ADMIN_PAT }}

      - name: Obtener URL de la Lambda
        id: get-lambda-url
        working-directory: infra/terraform
        run: |
          echo "== Obteniendo URL de Lambda =="
          LAMBDA_URL=$(terraform output -raw lambda_url)
          echo "URL obtenida: $LAMBDA_URL"
          echo "lambda_url=$LAMBDA_URL" >> $GITHUB_OUTPUT
          echo "============="

      - name: Verificar URL (opcional - para debug)
        run: |
          echo "La URL de la Lambda es: ${{ steps.get-lambda-url.outputs.lambda_url }}"

      - name: Ejecutar Lambda v√≠a curl
        run: |
          echo "Invocando Lambda en $LAMBDA_URL"
          curl -X POST ${{ steps.get-lambda-url.outputs.lambda_url }}
