name: Terraform Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'El entorno a desplegar'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - prod

jobs:
  terraform:
    name: Terraform Apply
    runs-on: ubuntu-latest
    steps:
      # Obtener el código
      - name: Checkout code
      ...
      - name: Checkout code
        uses: actions/checkout@v3

      # Configurar Terraform (misma versión que tu local)
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.13.4

      # Configurar credenciales de AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Inicializar Terraform
      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init -input=false

      # Crear plan
      - name: Terraform Plan
        working-directory: infra/terraform
        run: terraform plan -var-file="${{ github.event.inputs.environment }}.tfvars" -out=tfplan

      # Aplicar plan automáticamente
      - name: Terraform Apply
        working-directory: infra/terraform
        run: terraform apply -auto-approve tfplan

      # ===================================================
      # OBTENER OUTPUTS Y ACTUALIZAR SECRETS DE GITHUB
      # ===================================================
      - name: Exportar ECR URLs a secretos de GitHub
        working-directory: infra/terraform
        run: |
          # Obtener outputs de Terraform en JSON
          OUTPUTS=$(terraform output -json)

          # Extraer cada URL
          API=$(echo $OUTPUTS      | jq -r '.ecr_urls.value.apigateway')
          PRODUCT=$(echo $OUTPUTS  | jq -r '.ecr_urls.value.product')
          INVENTORY=$(echo $OUTPUTS| jq -r '.ecr_urls.value.inventory')

          echo "URL API Gateway: $API"
          echo "URL Product: $PRODUCT"
          echo "URL Inventory: $INVENTORY"

          # Actualizar secretos de GitHub
          gh secret set ECR_API_URL --body "$API"
          gh secret set ECR_PRODUCT_URL --body "$PRODUCT"
          gh secret set ECR_INVENTORY_URL --body "$INVENTORY"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
